### ISSUE TITLE
Add unit tests that test exported functions in src/

### ISSUE THREAD

**Issue by mstuart** [krakenjs/belter#10]
There are a LOT of useful utilities in belter, however there aren't any unit tests in this repo! 😬  If anyone's interested in picking this up, can you write unit tests for at least two files in src/? 😄

**Comment by kriscarilloxyz** [comment]
Mine

**Comment by mstuart** [comment]
All yours, @kriscarilloxyz !

**Comment by mstuart** [comment]
Hi @kriscarilloxyz! Still want to take this? Just checking in, so that we can give others a chance if you're busy. Thanks!

**Comment by kriscarilloxyz** [comment]
@mstuart Sorry, if anyone wanna step in feel free to do so, I'll be back on Monday if it's still open. Happy hacktoberfest everyone 🥳

**Comment by mstuart** [comment]
@pushpinder107 took this up w/ https://github.com/krakenjs/belter/pull/12 ! Thanks @pushpinder107 !

**Comment by mstuart** [comment]
Will keep this issue open in case anyone wants to add other unit tests!

**Comment by Cijin** [comment]
@mtstuart, Can I write tests for `src/dom.js` to bring coverage upto 100%. If it hasn't been taken up already.

**Comment by mnicpt** [comment]
@Cijin Absolutely!  Thanks, @Cijin !

**Comment by anthonykhoa** [comment]
@mstuart @mnicpt Hi, I can write tests for `src/experimental.js`!

**Comment by SlyBouhafs** [comment]
Hi @mstuart, i made a PR #24 to bring `src/css.js` test coverage to 100%.

**Comment by mstuart** [comment]
Thanks @SlyBouhafs ! :D

**Comment by songz** [comment]
> There are a LOT of useful utilities in belter, however there aren't any unit tests in this repo! 😬 If anyone's interested in picking this up, can you write unit tests for at least two files in src/?

@mstuart are these `unit tests`? Since they run end to end on Karma browser, they seem more like functional tests right?

**Comment by bluepnume** [comment]
I think they’re unit tests in the sense that they test individual functions in isolation — given that’s what belter exports.

But they’re not classic unit tests in two senses:

a) some of these utilities do a decent amount of orchestration and composition. So we’re testing multiple things at once rather than a small “unit” of logic

b) In these repos we try to only ever test the public interface, never the implementation (as much as possible). Typical unit tests can run against functions that are not part of the public interface, and also focus too much on implementation specifics. But I think that can lead to seriously brittle tests

**Comment by mstuart** [comment]
Looks like sufficient unit tests were added last year, so marking this as closed.
